parameters:
  buildConfig: ''                 # required -- build configuration
  archType: ''                    # required -- targeting CPU architecture
  osGroup: ''                     # required -- operating system for the job
  osSubgroup: ''                  # optional -- operating system subgroup
  condition: true
  pool: ''
  timeoutInMinutes: 180           # build timeout
  variables: {}
  helixQueues: ''
  dependOnEvaluatePaths: false
  runJobTemplate: '/eng/pipelines/coreclr/templates/run-superpmi-diffs-job.yml'

jobs:
- template: ${{ parameters.runJobTemplate }}
  parameters:
    jobName: ${{ format('superpmi_diffs_{0}{1}_{2}', parameters.osGroup, parameters.osSubgroup, parameters.archType) }}
    displayName: ${{ format('SuperPMI diffs {0}{1} {2}', parameters.osGroup, parameters.osSubgroup, parameters.archType) }}
    pool: ${{ parameters.pool }}
    buildConfig: ${{ parameters.buildConfig }}
    archType: ${{ parameters.archType }}
    osGroup: ${{ parameters.osGroup }}
    osSubgroup: ${{ parameters.osSubgroup }}
    condition: ${{ parameters.condition }}
    dependOnEvaluatePaths: ${{ parameters.dependOnEvaluatePaths }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    helixQueues: ${{ parameters.helixQueues }}
    dependsOn:
     # We depend on the Checked builds for asm diffs, and Release builds for TP diffs.
     - ${{ format('coreclr_jit_build_windows_x64_checked') }}
     - ${{ format('coreclr_jit_build_windows_x86_checked') }}
     - ${{ format('coreclr_jit_build_windows_x64_release') }}
     - ${{ format('coreclr_jit_build_windows_x86_release') }}

    variables:

    - ${{ each variable in parameters.variables }}:
      - ${{ if ne(variable.name, '') }}:
        - name: ${{ variable.name }}
          value: ${{ variable.value }}
      - ${{ if ne(variable.group, '') }}:
        - group: ${{ variable.group }}

    - name: ProductRootFolderPath_x64_checked
      value: '$(Build.SourcesDirectory)/artifacts/bin/coreclr/windows.x64.Checked'
    - name: ProductArtifactName_x64_checked
      value: 'CoreCLRProduct___windows_x64_checked'

    - name: ProductRootFolderPath_x64_release
      value: '$(Build.SourcesDirectory)/artifacts/bin/coreclr/windows.x64.Release'
    - name: ProductArtifactName_x64_release
      value: 'CoreCLRProduct___windows_x64_release'

    - name: ProductRootFolderPath_x86_checked
      value: '$(Build.SourcesDirectory)/artifacts/bin/coreclr/windows.x86.Checked'
    - name: ProductArtifactName_x86_checked
      value: 'CoreCLRProduct___windows_x86_checked'

    - name: ProductRootFolderPath_x86_release
      value: '$(Build.SourcesDirectory)/artifacts/bin/coreclr/windows.x86.Release'
    - name: ProductArtifactName_x86_release
      value: 'CoreCLRProduct___windows_x86_release'

    steps:

    # Download and unpack JIT builds

    - template: /eng/pipelines/common/download-artifact-step.yml
      parameters:
        unpackFolder: $(ProductRootFolderPath_x64_checked)
        artifactFileName: '$(ProductArtifactName_x64_checked)$(archiveExtension)'
        artifactName: '$(ProductArtifactName_x64_checked)'
        displayName: 'JIT x64 checked build'

    - template: /eng/pipelines/common/download-artifact-step.yml
      parameters:
        unpackFolder: $(ProductRootFolderPath_x86_checked)
        artifactFileName: '$(ProductArtifactName_x86_checked)$(archiveExtension)'
        artifactName: '$(ProductArtifactName_x86_checked)'
        displayName: 'JIT x86 checked build'

    - template: /eng/pipelines/common/download-artifact-step.yml
      parameters:
        unpackFolder: $(ProductRootFolderPath_x64_release)
        artifactFileName: '$(ProductArtifactName_x64_release)$(archiveExtension)'
        artifactName: '$(ProductArtifactName_x64_release)'
        displayName: 'JIT x64 release build'

    - template: /eng/pipelines/common/download-artifact-step.yml
      parameters:
        unpackFolder: $(ProductRootFolderPath_x86_release)
        artifactFileName: '$(ProductArtifactName_x86_release)$(archiveExtension)'
        artifactName: '$(ProductArtifactName_x86_release)'
        displayName: 'JIT x86 release build'